### ISSUE TITLE
Please provide clearer build instructions.

### ISSUE THREAD

**Issue by gl-yziquel** [dedis/apir-code#16]
Hi.

The README does not provide many build instructions.

The `make run_server` command builds the `server` executable just fine in `cmd/grpc/server`. But the `go run` command in that Makefile target fails because "id", "files" and "scheme" are not set, and I do not know to what I should attempt to set them.

I tried running `server` manually. I got:

```console
[Server -1] 2023/10/06 17:30:25 could not load the server config file: toml decoding: open config.toml: no such file or directory
```

This is terse. I have no example of such a `config.toml` file handy.

Please provide an easier pathway to having that code up and running.

**Comment by si-co** [comment]
Hi,

thank you for your questions. You have an example of `config.toml` file in the root of the repo: [config.toml](config.toml). Also, to run the server(s) and the client please refer to the [USENIX'23 artifact appendix](https://www.usenix.org/system/files/usenixsecurity23-appendix-colombo.pdf). 

I remain at your disposal for any further question.

**Comment by gl-yziquel** [comment]
How is the `config.toml` passed to the `server` executable ?

**Comment by si-co** [comment]
The `config.toml` file is passed to the server executable here: https://github.com/dedis/apir-code/blob/main/cmd/grpc/server/main.go#L82. I will reference the usenix appendix in the README.
